### ISSUE TITLE
Privatekey range predicate

### ISSUE THREAD

**Issue by pikachunakapika** [malb/bdd-predicate#12]
Hello and thank you again for the paper and the repository. Really interesting work!

I was wondering: 
If you know a key **x** is in a certain range below the order of the curve (e.g. 160bit key in a 256bit curve) could you increase the performance when there is a predicate for this range (159bit > **x** <161bit) as there are no calculations to publickey needed?

Best Regards
Marcel

**Comment by Hurd8x** [comment]
you need pubkey < 159 bit ? I can provide you key of puzzle trabdaction ballance 1.2 btc, privjey in 120 bit range and only 1 rsz outgoing transaction, or  geberate yoursef any  pubkey with this site

 https://secretscan.org/PrivateKeyHex

**Comment by Hurd8x** [comment]
I think you will need something like this crazy shit

https://bitcointalk.org/index.php?topic=5394249.0

**Comment by pikachunakapika** [comment]
COBRAS, you crazy are everywhere :). 
I am asking for a specific new predicate if it would help to increase the performance of this library.

**Comment by Hurd8x** [comment]
> COBRAS, you crazy are everywhere :). I am asking for a specific new predicate if it would help to increase the performance of this library in special cases.

you find secret exponent of any real blockchain like  btc or eth with  bdd-prwdicate ?

**Comment by pikachunakapika** [comment]
Well, this repository is bleeding edge if you want to find something...

**Comment by Hurd8x** [comment]
> 

ok.

Good luck, anyway !

**Comment by Hurd8x** [comment]
this fork of https://github.com/ellshea/bdd-predicate/projects?type=beta
