### ISSUE TITLE
public key

### ISSUE THREAD

**Issue by cloudkeychain** [malb/bdd-predicate#15]
Was having trouble figuring out how to convert uncompressed public key starting with 0x04 to public key starting with 308 like in sample input file. I converted to DER ASN.1 but it was double the length of PK in sample input. The RIPEMD256 hash i got was smaller length and started with 38 but not 308 so im not sure am able to figure out how to calculate the uncompressed public key to be compatible with sample input file starting with "308".

**Comment by Hurd8x** [comment]
add 04 before 308

**Comment by cloudkeychain** [comment]
so 04308 with the rest of uncompressed key following 308?

**Comment by cloudkeychain** [comment]
i tried uncompressed PK 04 and got overflow error: int too big to convert

**Comment by cloudkeychain** [comment]
> i tried uncompressed PK 04 and got overflow error: int too big to convert

should i try the compressed PK? That starts with 03?

**Comment by pikachunakapika** [comment]
Don't use compresse/uncompressed bitfcoin format. Use x and y with zero padding each to 64 characters.
