### ISSUE TITLE
publick keys and signatures ?

### ISSUE THREAD

**Issue by Hurd8x** [malb/bdd-predicate#7]
Help me please ?

😭

Thx

**Comment by eychei** [comment]
You have posted the following:

Good Day !!!

Help me please ?😂

sighnature details:

Z(hash of a message ?):

2bd8e1dfd43c0dcdb7310a2d29312a3a61c1430cf0b05df31069335f34e4a591

RS: 14d8b0457ee8711a1619ad1d29ed3f5bb5e511a5c1ebc4fd1023d79926c6f6fb5819780abbd0fe9a6da8559079f1ef0acecd2284e2212e9a4c4e5231e86fb7b4

Public key: 0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8

?

I try to move sach data to program input and get error sighnature and publick key not valid.

And this sighnature valid: Z: e01880a9ca1750fe7e66070bf6b8f5ceace6cff3bce4f3d803f8bea02fea9628

RS: d4fd78d94768318c422c2b82169c152810cae49b9a36d6adcb3bcb3e752728e61dfc81ec29fa40cb9b2adee3563fb3a2d9896f1ba4052b799a76b3d8433d3f5d

PublicKey: 04308cbd43c28357bd288c1a75d98a35597466697668a34582a193163eb8c66793f759cd81133dc0e238e192eddc17874994873bbcbae8ba3bab714d74f6939072

Help me please.

This is Bitcoin secp256k1 data !!! Yor code not work !!!

Why ?

________________________________


When recovering the public key using the R,S and Hash you will get two keys. For your signatures I get the following:
Z:
2bd8e1dfd43c0dcdb7310a2d29312a3a61c1430cf0b05df31069335f34e4a591
RS: 14d8b0457ee8711a1619ad1d29ed3f5bb5e511a5c1ebc4fd1023d79926c6f6fb5819780abbd0fe9a6da8559079f1ef0acecd2284e2212e9a4c4e5231e86fb7b4
Pub(1):
79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8
Pub(2):
aa1f8a996e83131cef412a9f4cb530ff4ebab9d8b584625fb91038eb20064f6ed3bff9d5fdfe5cdfe79a8178f3ff9b1bee09b2f60f1b199e651dee71eeb77ded

and for the second data:

Pub(1):
4260412fc17ad2679cf44105365f2ea3303a9bca6a54a7274293c082648557e2138991e2cdddfa5e69e5b2080ce7cf5048338acdcbf1176e3c090cbb34071cd2
Pub(2):
308cbd43c28357bd288c1a75d98a35597466697668a34582a193163eb8c66793f759cd81133dc0e238e192eddc17874994873bbcbae8ba3bab714d74f6939072

Why are you using the specified keys? 

-e

**Comment by Hurd8x** [comment]
> You have posted the following:
> 
> Good Day !!!
> 
> Help me please ?😂
> 
> sighnature details:
> 
> Z(hash of a message ?):
> 
> 2bd8e1dfd43c0dcdb7310a2d29312a3a61c1430cf0b05df31069335f34e4a591
> 
> RS: 14d8b0457ee8711a1619ad1d29ed3f5bb5e511a5c1ebc4fd1023d79926c6f6fb5819780abbd0fe9a6da8559079f1ef0acecd2284e2212e9a4c4e5231e86fb7b4
> 
> Public key: 0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8
> 
> ?
> 
> I try to move sach data to program input and get error sighnature and publick key not valid.
> 
> And this sighnature valid: Z: e01880a9ca1750fe7e66070bf6b8f5ceace6cff3bce4f3d803f8bea02fea9628
> 
> RS: d4fd78d94768318c422c2b82169c152810cae49b9a36d6adcb3bcb3e752728e61dfc81ec29fa40cb9b2adee3563fb3a2d9896f1ba4052b799a76b3d8433d3f5d
> 
> PublicKey: 04308cbd43c28357bd288c1a75d98a35597466697668a34582a193163eb8c66793f759cd81133dc0e238e192eddc17874994873bbcbae8ba3bab714d74f6939072
> 
> Help me please.
> 
> This is Bitcoin secp256k1 data !!! Yor code not work !!!
> 
> Why ?
> 
> When recovering the public key using the R,S and Hash you will get two keys. For your signatures I get the following: Z: 2bd8e1dfd43c0dcdb7310a2d29312a3a61c1430cf0b05df31069335f34e4a591 RS: 14d8b0457ee8711a1619ad1d29ed3f5bb5e511a5c1ebc4fd1023d79926c6f6fb5819780abbd0fe9a6da8559079f1ef0acecd2284e2212e9a4c4e5231e86fb7b4 Pub(1): 79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8 Pub(2): aa1f8a996e83131cef412a9f4cb530ff4ebab9d8b584625fb91038eb20064f6ed3bff9d5fdfe5cdfe79a8178f3ff9b1bee09b2f60f1b199e651dee71eeb77ded
> 
> and for the second data:
> 
> Pub(1): 4260412fc17ad2679cf44105365f2ea3303a9bca6a54a7274293c082648557e2138991e2cdddfa5e69e5b2080ce7cf5048338acdcbf1176e3c090cbb34071cd2 Pub(2): 308cbd43c28357bd288c1a75d98a35597466697668a34582a193163eb8c66793f759cd81133dc0e238e192eddc17874994873bbcbae8ba3bab714d74f6939072
> 
> Why are you using the specified keys?
> 
> -e

I using it for real experiments...

Why code not work with real data ? Help me please run code with my data ? Pleeeease ???
