### ISSUE TITLE
Why this points not on the curve ?

### ISSUE THREAD

**Issue by Hurd8x** [malb/bdd-predicate#9]
Input data:

252 de237edbda3fd84bfb67b30be74902d972aebd9eb36f7769d1cfdc6e8156f19b 59cc377724ef80404162374fbb09556a420226a4101c636ec46f82e8e5bbf77f122ca6ad80f5c7e26ff3a77dc486c1c8379ee4a248678367fd891d3d730b5ebd bd0a97710eb0f28d5ba6390264d2cc4e89258ce35bbd23462fb9e1c26a7ed706
252 990cb329df1f208a778435d206b047dcbaa6b2192edd98023bc8abe7f50ed6a1 a29e3a3da850dfb87bac64812b36aa6766cb444cc7cc4c0a1ddff0b20bc397955d8fdffc326f6f2d8a1160ec394e3a144f9f30903394de94993c11e5d6f9b3ad bd0a97710eb0f28d5ba6390264d2cc4e89258ce35bbd23462fb9e1c26a7ed706
252 cc40749aa45d3f3cc25d7e99d236880d1e1859125f09ec9d221d019e44fddb67 78c457e9523be207d0e5db5e438684ee6c2be41f69adcd6ce92ee764775a8f4f5a122a79552ee081160a94caf585f2c341007d69991e89e6304f19f9d948f690 15bcb400e69dea264290756359bfee55345755363693ba7d2edc90b356ea5757
252 9bed317d9eb855ed5dd4215ebbcf9b2bbee9d04c5109194e18deafac33f1f9ca 5a2fb5ef1d1a7a775808e957ee97707ed7aea55f42669a07dea9bdb4b94e80eb6e8b13ec9233ca0d2e4313189d0584267bbae1b0b2be361ae3074074da48ed40 15bcb400e69dea264290756359bfee55345755363693ba7d2edc90b356ea5757
252 50f27cb339b76c5fd1490dd45520ac1f710c5622f46ad5875cfc0692ff2be4b0 a38f18f213e37325098ae0950623307dfd42dfeea408d1aa96de1220395a02e203764980533ac527e37024cd8261809289d281a498105b4ac32ce6d338a70af0 15bcb400e69dea264290756359bfee55345755363693ba7d2edc90b356ea5757

???

Help me please ???

Best regard !

Test data in attachet file:
[28.txt](https://github.com/malb/bdd-predicate/files/7560709/28.txt)

**Comment by eychei** [comment]
Checking the first input data line i do get a different Pub. 
You got: bd0a97710eb0f28d5ba6390264d2cc4e89258ce35bbd23462fb9e1c26a7ed706

I get:

Pub(1): de3f4e88139ba1fba7c1509529082880c22dc2fe2c9f409b068c8c8bce40ef383ce4d422a97bf89b16dd001a3177cfd9beb27539815d489b512e73db4c785955 
Pub(2): 247b9803ad5091e2aadc6aa9bdda061f34861f3d5359298b68f8f340c09d5d5f1e2fc2ad056b34748e3ace46790b612393b207c0629ce99a75274484cd48d35c

**Comment by Hurd8x** [comment]
> Checking the first input data line i do get a different Pub. You got: bd0a97710eb0f28d5ba6390264d2cc4e89258ce35bbd23462fb9e1c26a7ed706
> 
> I get:
> 
> Pub(1): de3f4e88139ba1fba7c1509529082880c22dc2fe2c9f409b068c8c8bce40ef383ce4d422a97bf89b16dd001a3177cfd9beb27539815d489b512e73db4c785955 Pub(2): 247b9803ad5091e2aadc6aa9bdda061f34861f3d5359298b68f8f340c09d5d5f1e2fc2ad056b34748e3ace46790b612393b207c0629ce99a75274484cd48d35c

My data incorrect ! See please my txt file attached ? Pleeease.

**Comment by Hurd8x** [comment]
> Checking the first input data line i do get a different Pub. You got: bd0a97710eb0f28d5ba6390264d2cc4e89258ce35bbd23462fb9e1c26a7ed706
> 
> I get:
> 
> Pub(1): de3f4e88139ba1fba7c1509529082880c22dc2fe2c9f409b068c8c8bce40ef383ce4d422a97bf89b16dd001a3177cfd9beb27539815d489b512e73db4c785955 Pub(2): 247b9803ad5091e2aadc6aa9bdda061f34861f3d5359298b68f8f340c09d5d5f1e2fc2ad056b34748e3ace46790b612393b207c0629ce99a75274484cd48d35c

And with different pub, code not work too - incorrect sighnature, or publick key not on the curve I got error 😥

**Comment by Hurd8x** [comment]
> Checking the first input data line i do get a different Pub. You got: bd0a97710eb0f28d5ba6390264d2cc4e89258ce35bbd23462fb9e1c26a7ed706
> 
> I get:
> 
> Pub(1): de3f4e88139ba1fba7c1509529082880c22dc2fe2c9f409b068c8c8bce40ef383ce4d422a97bf89b16dd001a3177cfd9beb27539815d489b512e73db4c785955 Pub(2): 247b9803ad5091e2aadc6aa9bdda061f34861f3d5359298b68f8f340c09d5d5f1e2fc2ad056b34748e3ace46790b612393b207c0629ce99a75274484cd48d35c

Any help pleeeeeease ?

**Comment by Hurd8x** [comment]
I was message my ask about data format, about 3 weeks ago, Plleeease, help my run your code with my real data ?

**Comment by Hurd8x** [comment]
ile "/usr/lib/python3/dist-packages/click/core.py", line 764, in _
_call__                                                              
    return self.main(*args, **kwargs)                                
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in m
ain                                                                  
    rv = self.invoke(ctx)                                            
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in 
invoke                                                               
    return _process_result(sub_ctx.command.invoke(sub_ctx))          
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in i
nvoke                                                                
    return ctx.invoke(self.callback, **ctx.params)                   
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in i
nvoke                                                                
    return callback(*args, **kwargs)                                 
  File "ecdsa_cli.py", line 176, in solve                            
    solver = ECDSASolver(ecdsa, lines=lines, m=m, threads=parallelism
)                                                                    
  File "/home/ubuntu/bdd-predicate/ecdsa_hnp.py", line 191, in __init
__                                                                   
    assert self.vk.verify_digest(binascii.unhexlify(r + s), binascii.
unhexlify(h))                                                        
  File "/usr/local/lib/python3.8/dist-packages/ecdsa/keys.py", line 7
36, in verify_digest                                                 
    raise BadSignatureError("Signature verification failed")         
ecdsa.keys.BadSignatureError: Signature verification failed          
ubuntu@ip-172-31-65-90:~/bdd-predicate$

This is a log of error, help me please ?
